---
abstract: 'Packing Algorithm'
author:
  - 'JT Smith <jt@plainblack.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Box-Calc
requires:
  Log::Any: 0
  Moose: 0
  Ouch: 0.0400
  Test::Deep: 0
  Test::More: 0
resources:
  bugtracker: http://github.com/rizen/Box-Calc/issues
  repository: git://github.com/rizen/Box-Calc.git
version: 0.0101
